src/Entity/User/Address.php
<?php

namespace App\Entity\User;

use App\Entity\EntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="t_addresses")
 */
class Address implements EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $address_1;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $address_2;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $zip;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $county;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User\Profile",mappedBy="address")
     */
    private $profile;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getAddress1()
    {
        return $this->address_1;
    }

    /**
     * @param mixed $address_1
     */
    public function setAddress1($address_1): void
    {
        $this->address_1 = $address_1;
    }

    /**
     * @return mixed
     */
    public function getAddress2()
    {
        return $this->address_2;
    }

    /**
     * @param mixed $address_2
     */
    public function setAddress2($address_2): void
    {
        $this->address_2 = $address_2;
    }

    /**
     * @return mixed
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * @param mixed $zip
     */
    public function setZip($zip): void
    {
        $this->zip = $zip;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     */
    public function setCity($city): void
    {
        $this->city = $city;
    }

    /**
     * @return mixed
     */
    public function getCounty()
    {
        return $this->county;
    }

    /**
     * @param mixed $county
     */
    public function setCounty($county): void
    {
        $this->county = $county;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return mixed
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * @param mixed $profile
     */
    public function setProfile($profile): void
    {
        $this->profile = $profile;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return string|null
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * @param string|null $country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }
}

src/Entity/User/Balance.php
<?php

namespace App\Entity\User;

use App\Entity\BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="t_balances")
 */
class Balance extends BaseEntity
{

    /**
     * @ORM\Column(type="float",scale=2,precision=10,options={"default":0})
     */
    private $total;

    /**
     * @ORM\Column(type="float",scale=2,precision=10,nullable=true,options={"default":0})
     */
    private $blocked;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User\User",inversedBy="balance")
     */
    private $user;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $payout;

    public function __construct(?User $user = null)
    {
        $this->user = $user;
        $this->total = 0;
        $this->blocked = 0;
    }

    /**
     * @return mixed
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * @param mixed $total
     */
    public function setTotal($total): void
    {
        $this->total = $total;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getPayout()
    {
        return $this->payout;
    }

    /**
     * @param mixed $payout
     */
    public function setPayout($payout): void
    {
        $this->payout = $payout;
    }

    /**
     * @return mixed
     */
    public function getBlocked()
    {
        return $this->blocked;
    }

    /**
     * @param mixed $blocked
     */
    public function setBlocked($blocked): void
    {
        $this->blocked = $blocked;
    }
}

src/Form/Type/SettingsType.php
<?php

namespace App\Form\Type;

use App\Entity\User\Settings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SettingsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('isPortfolioVisible')
            ->add('isEmailNotificationAllowed')
            ->add('isWebNotificationAllowed')
            ->add('isPushNotificationAllowed')
            ->add('showNudes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Settings::class,
        ]);
    }
}

src/Form/Type/UserType.php
<?php

namespace App\Form\Type;

use App\Entity\User\User;
use App\Repository\ConfigurationRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class UserType
 * @package App\Form\Type
 */
class UserType extends AbstractType
{
    /**
     * @var ConfigurationRepository
     */
    private ConfigurationRepository $configurationRepository;

    /**
     * UserType constructor.
     * @param ConfigurationRepository $configurationRepository
     */
    public function __construct(ConfigurationRepository $configurationRepository)
    {
        $this->configurationRepository = $configurationRepository;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('profile', ProfileType::class);

        if ($this->configurationRepository->getConfig()->getAllowShopping()) {
            $builder->add('balance', BalanceType::class);
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/Easyadmin/UserController.php
<?php

namespace App\Controller\Admin\Easyadmin;

use App\Entity\User\Balance;
use App\Entity\User\User;
use App\EntityManager\AlbumManager;
use App\EntityManager\BaseManager;
use App\EntityManager\MessageManager;
use App\EntityManager\NotificationManager;
use App\EntityManager\PostManager;
use App\Enum\FileStorageFolderEnum;
use App\Enum\ImageSizeEnum;
use App\FileManager\S3FileManager;
use App\Processor\ImageProcessor;
use App\Repository\ConfigurationRepository;
use EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController;
use ImagickException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * Class UserController
 * @package App\Controller\Admin\Easyadmin
 */
class UserController extends BaseController
{
    /**
     * @var BaseManager
     */
    private BaseManager $settingsManager;

    /**
     * @var BaseManager
     */
    private BaseManager $cartManager;

    /**
     * @var S3FileManager
     */
    private S3FileManager $fileManager;

    /**
     * @var PostManager
     */
    private PostManager $postManager;

    /**
     * @var BaseManager
     */
    private BaseManager $balanceManager;

    /**
     * @var ImageProcessor
     */
    private ImageProcessor $imageProcessor;

    /**
     * @var UserPasswordEncoderInterface
     */
    private UserPasswordEncoderInterface $encoder;

    /**
     * @var BaseManager|PostManager
     */
    private $albumManager;

    /**
     * @var NotificationManager
     */
    private NotificationManager $notificationManager;

    /**
     * @var BaseManager
     */
    private BaseManager $commentManager;

    /**
     * @var BaseManager
     */
    private BaseManager $replyManager;

    /**
     * @var BaseManager
     */
    private BaseManager $topicManager;

    /**
     * @var BaseManager
     */
    private BaseManager $opinionManager;

    /**
     * @var MessageManager
     */
    private MessageManager $messageManager;

    /**
     * @var BaseManager
     */
    private BaseManager $curateManager;

    /**
     * @var BaseManager
     */
    private BaseManager $voteManager;

    /**
     * @var ConfigurationRepository
     */
    private ConfigurationRepository $configurationRepository;

    /**
     * UserController constructor.
     * @param BaseManager $settingsManager
     * @param BaseManager $cartManager
     * @param BaseManager $balanceManager
     * @param BaseManager $commentManager
     * @param BaseManager $replyManager
     * @param BaseManager $topicManager
     * @param BaseManager $opinionManager
     * @param BaseManager $curateManager
     * @param BaseManager $voteManager
     * @param MessageManager $messageManager
     * @param PostManager $postManager
     * @param NotificationManager $notificationManager
     * @param AlbumManager $albumManager
     * @param ConfigurationRepository $configurationRepository
     * @param UserPasswordEncoderInterface $encoder
     * @param ImageProcessor $imageProcessor
     * @param S3FileManager $fileManager
     */
    public function __construct(BaseManager $settingsManager,
                                BaseManager $cartManager,
                                BaseManager $balanceManager,
                                BaseManager $commentManager,
                                BaseManager $replyManager,
                                BaseManager $topicManager,
                                BaseManager $opinionManager,
                                BaseManager $curateManager,
                                BaseManager $voteManager,
                                MessageManager $messageManager,
                                PostManager $postManager,
                                NotificationManager $notificationManager,
                                AlbumManager $albumManager,
                                ConfigurationRepository $configurationRepository,
                                UserPasswordEncoderInterface $encoder,
                                ImageProcessor $imageProcessor,
                                S3FileManager $fileManager)
    {
        $this->settingsManager = $settingsManager;
        $this->cartManager = $cartManager;
        $this->fileManager = $fileManager;
        $this->postManager = $postManager;
        $this->balanceManager = $balanceManager;
        $this->imageProcessor = $imageProcessor;
        $this->encoder = $encoder;
        $this->albumManager = $albumManager;
        $this->notificationManager = $notificationManager;
        $this->commentManager = $commentManager;
        $this->replyManager = $replyManager;
        $this->topicManager = $topicManager;
        $this->opinionManager = $opinionManager;
        $this->messageManager = $messageManager;
        $this->curateManager = $curateManager;
        $this->voteManager = $voteManager;
        $this->configurationRepository = $configurationRepository;
    }

    /**
     * @param object $entity
     * @throws ImagickException
     */
    protected function persistEntity($entity)
    {
        $this->upload($entity);
        $this->encodePassword($entity);

        parent::persistEntity($entity);
    }

    /**
     * @param object $entity
     * @throws ImagickException
     */
    protected function updateEntity($entity)
    {
        $this->upload($entity);
        $this->encodePassword($entity);

        parent::updateEntity($entity);

    }

    /**
     * @param User $entity
     */
    protected function removeEntity($entity)
    {
        /**
         * @var Balance $balance
         */
        $balance = $this->balanceManager->repository->findOneBy(['user' => $entity], [], false);

        if (($balance && ($balance->getBlocked() > 0 || $balance->getTotal() > 0)) || $entity->getDeletionDate() === null) {

            if ($entity->getDeletionDate() === null) {

                $deletionDate = (new \DateTime())->modify("+ {$this->configurationRepository->getConfig()->getPostDeletionInterval()} days");

                foreach ($entity->getPosts() as $post) {

                    $post->setDeletionDate($deletionDate);

                    foreach ($post->getChildren() as $child) {
                        $child->setDeletionDate($deletionDate);
                        $this->postManager->delete($child);
                    }

                    $this->postManager->delete($post);
                }

                $entity->setDeletionDate($deletionDate);
                $entity->setIsDeleted(true);
            }

        } else {

            if ($entity->getDeletionDate() < new \DateTime()) {

                if ($balance) {
                    $this->balanceManager->delete($balance, false);
                }

                foreach ($entity->getPosts() as $post) {

                    $post->setUser(null);

                    foreach ($post->getChildren() as $child) {
                        $child->setUser(null);
                    }

                }

                $entity->setIsDeleted(true);
            }

        }

        $settings = $this->settingsManager->repository->findOneBy(['user' => $entity], [], false);

        if ($settings) {
            $this->settingsManager->delete($settings, false);
        }

        $cart = $this->cartManager->repository->findOneBy(['user' => $entity], [], false);
        if ($cart) {
            $this->cartManager->delete($cart, false);
        }

        $albums = $this->albumManager->repository->findBy(['user' => $entity]);

        foreach ($albums as $album) {
            $this->albumManager->delete($album, false);
        }

        $replies = $this->replyManager->repository->findBy(['user' => $entity]);

        foreach ($replies as $reply) {
            $this->replyManager->delete($reply, false);
        }

        $comments = $this->commentManager->repository->findBy(['user' => $entity]);

        foreach ($comments as $comment) {
            $this->commentManager->delete($comment, false);
        }

        $votes = $this->voteManager->repository->findBy(['voter' => $entity]);

        foreach ($votes as $vote) {
            $this->voteManager->delete($vote, false);
        }

        $notifications = $this->notificationManager->repository->findBy(['sender' => $entity]);

        foreach ($notifications as $notification) {
            $this->notificationManager->delete($notification, false);
        }

        $notifications = $this->notificationManager->repository->findBy(['receiver' => $entity]);

        foreach ($notifications as $notification) {
            $this->notificationManager->delete($notification, false);
        }

        $topics = $this->topicManager->repository->findBy(['owner' => $entity]);

        foreach ($topics as $topic) {
            $this->topicManager->delete($topic, false);
        }

        $opinions = $this->opinionManager->repository->findBy(['user' => $entity]);

        foreach ($opinions as $opinion) {
            $this->opinionManager->delete($opinion, false);
        }

        $messages = $this->messageManager->repository->findBy(['sender' => $entity]);

        foreach ($messages as $message) {
            $this->messageManager->delete($message, false);
        }

        $messages = $this->messageManager->repository->findBy(['receiver' => $entity]);

        foreach ($messages as $message) {
            $this->messageManager->delete($message, false);
        }

        $curates = $this->curateManager->repository->findBy(['users' => $entity]);

        foreach ($curates as $curate) {
            $this->curateManager->delete($curate, false);
        }

    }

    /**
     * Upload cover and picture
     *
     * @param User $entity
     *
     * @throws ImagickException
     */
    protected function upload($entity)
    {

        if ($entity->getProfile()->getPictureFile() instanceof UploadedFile) {

templates/user/settings/general.html.twig
{% extends 'template.html.twig' %}

{% block title %}Site Settings{% endblock %}

{% block header_left %}Site Settings{% endblock %}

{% block header_right %}

    <a href="{{ app.request.session.get('back') ?? path('web_profile_edit') }}">
        <i class="fas fa-times"></i>
    </a>

{% endblock %}

{% block main_content %}


    <div class="col-12">
        {{ form_start(form) }}

        <h6>Notifications:</h6>
        <hr class="no-gutter">
        <label class="custom-control custom-checkbox">
            {{ form_widget(form.isEmailNotificationAllowed,{attr:{class:'custom-control-input'}}) }}
            <span class="custom-control-indicator"></span>
            Receive Email notifications
        </label>

        <label class="custom-control custom-checkbox">
            {{ form_widget(form.isWebNotificationAllowed,{attr:{class:'custom-control-input'}}) }}
            <span class="custom-control-indicator"></span>
            Receive Web notifications (Website Notifications)
        </label>

        <label class="custom-control custom-checkbox">
            {{ form_widget(form.isPushNotificationAllowed,{attr:{class:'custom-control-input'}}) }}
            <span class="custom-control-indicator"></span>
            Receive Push notifications (Phone App Notifications)
        </label>

        <h6 class="mt-5">General settings:</h6>
        <hr class="no-gutter">
        <label class="custom-control custom-checkbox">
            {{ form_widget(form.showNudes,{attr:{class:'custom-control-input'}}) }}
            <span class="custom-control-indicator"></span>
            Show nude content
        </label>

        <label class="custom-control custom-checkbox">
            {{ form_widget(form.isPortfolioVisible,{attr:{class:'custom-control-input'}}) }}
            <span class="custom-control-indicator"></span>
            Visible Uploads
        </label>

        <hr>

        <button class="btn btn-info">Save</button>

        {{ form_end(form) }}
    </div>


{% endblock %}

templates/user/settings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Account Settings{% endblock %}

{% block css %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.1/cropper.min.css">
{% endblock %}

{% block body %}

    <div class="profile-settings-page">

        <div class="container-fluid profile" style="max-width: 1200px">

            <div class="row">

                <div class="cover">

                    <label for="cover" class="btn btn-warning">
                        <input id="cover" type="file" accept="image/jpeg"/>
                        Upload
                    </label>

                    <div class="options">

                        <button class="btn btn-primary" id="save" type="button">
                            <i class="fas fa-check"></i>
                        </button>

                        <button class="btn btn-danger shadow" id="cancel" type="button">
                            <i class="fas fa-times"></i>
                        </button>

                    </div>

                    <small class="text-muted bg-white p-2 rounded  position-absolute" style="right:10px;top:10px;">
                        Recommended size: 1200x350 px
                    </small>

                    <img src="{{ user.profile.cover ?? asset('images/cover.jpg') }}" id="cover-image"
                         alt="Cover"/>

                    <img src="" id="cover-image-cropper" alt="Cover"/>

                    <div class="dots-loader"></div>

                </div>

            </div>

        </div>

        <div class="container basic-layout profile-meta" style="max-width: 1200px">

            <div class="row" style="padding-bottom: 3.5rem">

                <div class="col-lg-2">

                    <div class="profile-avatar profile-avatar-settings circle text-center">

                        <div class="avatar-loader"></div>

                        <img src="{{ form.profile.vars.value.picture ?? asset('images/avatar.jpg') }}"
                             alt="Profile Picture"
                             class="shadow circle">

                        <input type="file" id="avatar" accept="image/jpeg,image/png" class="circle"/>

                    </div>

                </div>

                <div class="col-lg-10">

                    <div class="profile-info mt-lg-n5 mt-0 text-center text-lg-left">

                        <h1>
                            <strong>
                                {{ user.profile.firstName }} {{ user.profile.lastName }}
                            </strong>
                        </h1>


                        <div class="mt-3">

                            <i class="fa fa-lock"></i>
                            <a href="{{ path('web_change_password') }}">
                                Change Password
                            </a>

                            <i class="fas fa-wrench ml-4"></i>
                            <a href="{{ path('web_settings') }}">
                                Site Settings
                            </a>

                        </div>

                    </div>

                </div>

            </div>

        </div>

        <div class="container basic-layout mt-5">

            {{ form_start(form) }}

            <div class="row default-form-layout">

                <div class="col-md-6 col-sm-6">

                    <h3 class="text-muted">Personal Details:</h3>

                    <hr>

                    <div class="form-group">
                        {{ form_label(form.profile.firstName) }}
                        {{ form_widget(form.profile.firstName,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.lastName) }}
                        {{ form_widget(form.profile.lastName,{attr:{class:'form-control'}}) }}
                    </div>

                    {% if form.balance is defined %}
                        <div class="form-group">
                            {{ form_label(form.balance.payout,'Paypal Email') }}
                            {{ form_widget(form.balance.payout,{attr:{class:'form-control'}}) }}
                        </div>
                    {% endif %}

                    <h3 class="text-muted">Social:</h3>

                    <hr>

                    <div class="form-group">
                        {{ form_label(form.profile.facebook) }}
                        {{ form_widget(form.profile.facebook,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.twitter) }}
                        {{ form_widget(form.profile.twitter,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.instagram) }}
                        {{ form_widget(form.profile.instagram,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.website) }}
                        {{ form_widget(form.profile.website,{attr:{class:'form-control'}}) }}
                    </div>

                </div>

                <div class="col-md-6 col-sm-6">

                    <h3 class="text-muted">Address:</h3>

                    <hr>

                    <div class="form-group">
                        {{ form_label(form.profile.nationality) }}
                        {{ form_widget(form.profile.nationality,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.country) }}
                        {{ form_widget(form.profile.address.country,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.county) }}
                        {{ form_widget(form.profile.address.county,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.address1) }}
                        {{ form_widget(form.profile.address.address1,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.address2) }}
                        {{ form_widget(form.profile.address.address2,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.zip) }}
                        {{ form_widget(form.profile.address.zip,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.city) }}
                        {{ form_widget(form.profile.address.city,{attr:{class:'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.profile.address.phone) }}
                        {{ form_widget(form.profile.address.phone,{attr:{class:'form-control'}}) }}
                    </div>

                </div>

            </div>

            <div class="row">

                <div class="col-12 text-center">

                    <hr>

                    <button class="btn btn-info">
                        Save
                    </button>

                </div>

            </div>

            {{ form_end(form) }}

        </div>

    </div>

{% endblock %}

{% block js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.1/cropper.min.js"></script>
    <script src="{{ asset('js/cover-cropper.js') }}"></script>
{% endblock %}

templates/user/settings/password.html.twig
{% extends 'template.html.twig' %}

{% block title %}Change Password{% endblock %}

{% block header_left %}Change Password{% endblock %}

{% block header_right %}

    <a href="{{ app.request.session.get('back') ?? path('web_profile_edit') }}">
        <i class="fas fa-times"></i>
    </a>

{% endblock %}

{% block main_content %}

    <div class="col-12">

        {{ form_start(form) }}

        {{ form_errors(form) }}

        {% if form.oldPassword is defined %}
            <div class="form-group">
                {{ form_label(form.oldPassword, 'Old Password:') }}
                {{ form_widget(form.oldPassword,{attr:{class:'form-control'}}) }}
            </div>
        {% endif %}

        <div class="form-group">
            {{ form_label(form.password.first, 'New Password:') }}
            {{ form_widget(form.password.first,{attr:{class:'form-control'}}) }}
        </div>

        <div class="form-group">
            {{ form_label(form.password.second, 'Repeat New Password:') }}
            {{ form_widget(form.password.second,{attr:{class:'form-control'}}) }}
        </div>

        <hr>

        <div class="form-group">
            <button class="btn btn-info">
                Change
            </button>
        </div>

        {{ form_end(form) }}

    </div>

{% endblock %}